services:
  sqlserver:
    env_file: "SurfSessions-API.env"
    image: mcr.microsoft.com/mssql/server:2022-CU18-ubuntu-22.04
    container_name: sqlserver-surfsessions
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - "1435:1435"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: